version: "3"
services:
  worker:
    image: "mukulkumra/demo-react-app-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  client:
    image: "mukulkumra/demo-react-app-ui"
    mem_limit: 128m
    hostname: client
    ports:
      - "80:80"
  api:
    image: "mukulkumra/demo-react-app-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_PORT=$REDIS_PORT
      - REDIS_HOST=$REDIS_HOST
      - PG_HOST=$PG_HOST
      - PG_DATABASE=$PG_DATABASE
      - PG_PASSWORD=$PG_PASSWORD
      - PG_PORT=$PG_PORT
      - PG_USER=$PG_USER
